// This is a generated file. DO NOT EDIT.

package freetype

// #cgo pkg-config: freetype2
//
// #include <ft2build.h>
// #include FT_FREETYPE_H
import "C"

const FT_ENC_TAG = C.FT_ENC_TAG
const FT_FACE_FLAG_SCALABLE = C.FT_FACE_FLAG_SCALABLE
const FT_FACE_FLAG_FIXED_SIZES = C.FT_FACE_FLAG_FIXED_SIZES
const FT_FACE_FLAG_FIXED_WIDTH = C.FT_FACE_FLAG_FIXED_WIDTH
const FT_FACE_FLAG_SFNT = C.FT_FACE_FLAG_SFNT
const FT_FACE_FLAG_HORIZONTAL = C.FT_FACE_FLAG_HORIZONTAL
const FT_FACE_FLAG_VERTICAL = C.FT_FACE_FLAG_VERTICAL
const FT_FACE_FLAG_KERNING = C.FT_FACE_FLAG_KERNING
const FT_FACE_FLAG_FAST_GLYPHS = C.FT_FACE_FLAG_FAST_GLYPHS
const FT_FACE_FLAG_MULTIPLE_MASTERS = C.FT_FACE_FLAG_MULTIPLE_MASTERS
const FT_FACE_FLAG_GLYPH_NAMES = C.FT_FACE_FLAG_GLYPH_NAMES
const FT_FACE_FLAG_EXTERNAL_STREAM = C.FT_FACE_FLAG_EXTERNAL_STREAM
const FT_FACE_FLAG_HINTER = C.FT_FACE_FLAG_HINTER
const FT_FACE_FLAG_CID_KEYED = C.FT_FACE_FLAG_CID_KEYED
const FT_FACE_FLAG_TRICKY = C.FT_FACE_FLAG_TRICKY
const FT_FACE_FLAG_COLOR = C.FT_FACE_FLAG_COLOR
const FT_FACE_FLAG_VARIATION = C.FT_FACE_FLAG_VARIATION
const FT_FACE_FLAG_SVG = C.FT_FACE_FLAG_SVG
const FT_FACE_FLAG_SBIX = C.FT_FACE_FLAG_SBIX
const FT_FACE_FLAG_SBIX_OVERLAY = C.FT_FACE_FLAG_SBIX_OVERLAY
const FT_HAS_HORIZONTAL = C.FT_HAS_HORIZONTAL
const FT_HAS_VERTICAL = C.FT_HAS_VERTICAL
const FT_HAS_KERNING = C.FT_HAS_KERNING
const FT_IS_SCALABLE = C.FT_IS_SCALABLE
const FT_IS_SFNT = C.FT_IS_SFNT
const FT_IS_FIXED_WIDTH = C.FT_IS_FIXED_WIDTH
const FT_HAS_FIXED_SIZES = C.FT_HAS_FIXED_SIZES
const FT_HAS_FAST_GLYPHS = C.FT_HAS_FAST_GLYPHS
const FT_HAS_GLYPH_NAMES = C.FT_HAS_GLYPH_NAMES
const FT_HAS_MULTIPLE_MASTERS = C.FT_HAS_MULTIPLE_MASTERS
const FT_IS_NAMED_INSTANCE = C.FT_IS_NAMED_INSTANCE
const FT_IS_VARIATION = C.FT_IS_VARIATION
const FT_IS_CID_KEYED = C.FT_IS_CID_KEYED
const FT_IS_TRICKY = C.FT_IS_TRICKY
const FT_HAS_COLOR = C.FT_HAS_COLOR
const FT_HAS_SVG = C.FT_HAS_SVG
const FT_HAS_SBIX = C.FT_HAS_SBIX
const FT_HAS_SBIX_OVERLAY = C.FT_HAS_SBIX_OVERLAY
const FT_STYLE_FLAG_ITALIC = C.FT_STYLE_FLAG_ITALIC
const FT_STYLE_FLAG_BOLD = C.FT_STYLE_FLAG_BOLD
const FT_OPEN_MEMORY = C.FT_OPEN_MEMORY
const FT_OPEN_STREAM = C.FT_OPEN_STREAM
const FT_OPEN_PATHNAME = C.FT_OPEN_PATHNAME
const FT_OPEN_DRIVER = C.FT_OPEN_DRIVER
const FT_OPEN_PARAMS = C.FT_OPEN_PARAMS
const FT_LOAD_DEFAULT = C.FT_LOAD_DEFAULT
const FT_LOAD_NO_SCALE = C.FT_LOAD_NO_SCALE
const FT_LOAD_NO_HINTING = C.FT_LOAD_NO_HINTING
const FT_LOAD_RENDER = C.FT_LOAD_RENDER
const FT_LOAD_NO_BITMAP = C.FT_LOAD_NO_BITMAP
const FT_LOAD_VERTICAL_LAYOUT = C.FT_LOAD_VERTICAL_LAYOUT
const FT_LOAD_FORCE_AUTOHINT = C.FT_LOAD_FORCE_AUTOHINT
const FT_LOAD_CROP_BITMAP = C.FT_LOAD_CROP_BITMAP
const FT_LOAD_PEDANTIC = C.FT_LOAD_PEDANTIC
const FT_LOAD_IGNORE_GLOBAL_ADVANCE_WIDTH = C.FT_LOAD_IGNORE_GLOBAL_ADVANCE_WIDTH
const FT_LOAD_NO_RECURSE = C.FT_LOAD_NO_RECURSE
const FT_LOAD_IGNORE_TRANSFORM = C.FT_LOAD_IGNORE_TRANSFORM
const FT_LOAD_MONOCHROME = C.FT_LOAD_MONOCHROME
const FT_LOAD_LINEAR_DESIGN = C.FT_LOAD_LINEAR_DESIGN
const FT_LOAD_SBITS_ONLY = C.FT_LOAD_SBITS_ONLY
const FT_LOAD_NO_AUTOHINT = C.FT_LOAD_NO_AUTOHINT
const FT_LOAD_COLOR = C.FT_LOAD_COLOR
const FT_LOAD_COMPUTE_METRICS = C.FT_LOAD_COMPUTE_METRICS
const FT_LOAD_BITMAP_METRICS_ONLY = C.FT_LOAD_BITMAP_METRICS_ONLY
const FT_LOAD_NO_SVG = C.FT_LOAD_NO_SVG
const FT_LOAD_ADVANCE_ONLY = C.FT_LOAD_ADVANCE_ONLY
const FT_LOAD_SVG_ONLY = C.FT_LOAD_SVG_ONLY
const FT_LOAD_TARGET_ = C.FT_LOAD_TARGET_
const FT_LOAD_TARGET_NORMAL = C.FT_LOAD_TARGET_NORMAL
const FT_LOAD_TARGET_LIGHT = C.FT_LOAD_TARGET_LIGHT
const FT_LOAD_TARGET_MONO = C.FT_LOAD_TARGET_MONO
const FT_LOAD_TARGET_LCD = C.FT_LOAD_TARGET_LCD
const FT_LOAD_TARGET_LCD_V = C.FT_LOAD_TARGET_LCD_V
const FT_LOAD_TARGET_MODE = C.FT_LOAD_TARGET_MODE
const FT_SUBGLYPH_FLAG_ARGS_ARE_WORDS = C.FT_SUBGLYPH_FLAG_ARGS_ARE_WORDS
const FT_SUBGLYPH_FLAG_ARGS_ARE_XY_VALUES = C.FT_SUBGLYPH_FLAG_ARGS_ARE_XY_VALUES
const FT_SUBGLYPH_FLAG_ROUND_XY_TO_GRID = C.FT_SUBGLYPH_FLAG_ROUND_XY_TO_GRID
const FT_SUBGLYPH_FLAG_SCALE = C.FT_SUBGLYPH_FLAG_SCALE
const FT_SUBGLYPH_FLAG_XY_SCALE = C.FT_SUBGLYPH_FLAG_XY_SCALE
const FT_SUBGLYPH_FLAG_2X2 = C.FT_SUBGLYPH_FLAG_2X2
const FT_SUBGLYPH_FLAG_USE_MY_METRICS = C.FT_SUBGLYPH_FLAG_USE_MY_METRICS
const FT_FSTYPE_INSTALLABLE_EMBEDDING = C.FT_FSTYPE_INSTALLABLE_EMBEDDING
const FT_FSTYPE_RESTRICTED_LICENSE_EMBEDDING = C.FT_FSTYPE_RESTRICTED_LICENSE_EMBEDDING
const FT_FSTYPE_PREVIEW_AND_PRINT_EMBEDDING = C.FT_FSTYPE_PREVIEW_AND_PRINT_EMBEDDING
const FT_FSTYPE_EDITABLE_EMBEDDING = C.FT_FSTYPE_EDITABLE_EMBEDDING
const FT_FSTYPE_NO_SUBSETTING = C.FT_FSTYPE_NO_SUBSETTING
const FT_FSTYPE_BITMAP_EMBEDDING_ONLY = C.FT_FSTYPE_BITMAP_EMBEDDING_ONLY
